export const musicSources = [
    {name: 'Hot 100 | Billboard', value: 'hot-100', showDatePicker: true, source: 'billboard'},
    {name: 'Artist 100 | Billboard', value: 'artist-100', showDatePicker: true, source: 'billboard'},
    {name: 'Top Streaming Songs | Billboard', value: 'streaming-songs', showDatePicker: true,  source: 'billboard'},
    {name: 'Pop Airplay | Billboard', value: 'pop-songs', showDatePicker: true, source: 'billboard'},
    {name: 'Hot Dance Songs | Billboard', value: 'dance-electronic-songs', showDatePicker: true, source: 'billboard'},
    {name: 'Hot Rock Songs | Billboard', value: 'hot-rock-songs', showDatePicker: true, source: 'billboard'},
    {name: 'Mainstream Rock Airplay | Billboard', value: 'hot-mainstream-rock-tracks', showDatePicker: true, source: 'billboard'},
    {name: 'Top Rock & Alternative Albums | Billboard', value: 'top-rock-alternative-albums', showDatePicker: true, source: 'billboard'},
    {name: 'Hot Alternative Songs | Billboard', value: 'hot-alternative-songs', showDatePicker: true, source: 'billboard'},
    {name: 'Alternative Streaming Songs | Billboard', value: 'alternative-streaming-songs', showDatePicker: true, source: 'billboard'},
    {name: 'Spotify | Kworb', value: 'spotify', source: 'kworb', showPeriodPicker: true, showCountryPicker: true},
    {name: 'Youtube Most Viewed Daily | Kworb', value: 'youtube', source: 'kworb'},
    {name: 'Youtube Most Viewed Daily - English | Kworb', value: 'youtube-realtime_anglo.html', source: 'kworb'},
    {name: 'Top Trending | Last.fm', value: 'lastfm', source: 'lastfm'},
]
